{{- if .Values.gateway.dataSources.kubernetes.enabled }}
{{- if (include "gateway.mode.isIngress" .) }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ (include "ingressClass.name" .) }}
  {{- if .Values.ingressClass.setAsDefault }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: {{ (include "ingressClass.controllerValue" .) }}
{{- end }}
{{- end }}
