name: cRUL status

on:
  push:
    branches:
      - main

jobs:
  cURL:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none

    steps:
      - name: test cURL status code
        run: |
          http_code=$(curl -so /dev/null -w "%{http_code}" https://www.google.com/news)
          echo "http_code -> $http_code"
          if [[ $http_code == 200 ]]; then
            echo "Success"
          else
            echo "Failed"
          fi
