name: date-time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
      branches:
        - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1
  name: "nadeem"

jobs:
  DateTime:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version

      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: get expiration date
        run: |

          current_timestamp=$(date +%s)
          echo "current_timestamp -> $current_timestamp"

          #get expiration timestamp from reg-time.json

          jq . reg-time.json

          future_date="$(jq -r '.expiration_date[:19]' reg-time.json)"
          future_timestamp=$(date -d "$future_date" +%s)
          echo "future_timestamp -> $future_timestamp"

          time_diff=$(($future_timestamp - $current_timestamp))
          echo "time_diff -> $time_diff"

          days=$(($time_diff / 86400))
          echo "days -> $days"

          if [[ $days -lt 7 ]]; then
            echo "Less than 7 days left"
            RENEW=true
          else
            echo "More than 7 days left"
            RENEW=false
          fi

          echo "RENEW -> $RENEW"

      - name: call function
        run: |
          echo "workspace -> ${GITHUB_WORKSPACE}"
          message=$(bash hello.sh "nadeem")
          echo "message is $message"



      
          


          