name: date-time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
      branches:
        - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1
  name: "nadeem"

jobs:
  DateTime:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version

      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: get expiration date
        id: date
        run: |

          current_timestamp=$(date +%s)
          echo "current_timestamp -> $current_timestamp"

          #get expiration timestamp from reg-time.json

          jq . reg-time.json

          future_date="$(jq -r '.expiration_date[:19]' reg-time.json)"
          future_timestamp=$(date -d "$future_date" +%s)
          echo "future_timestamp -> $future_timestamp"

          time_diff=$(($future_timestamp - $current_timestamp))
          echo "time_diff -> $time_diff"

          days=$(($time_diff / 86400))
          echo "days -> $days"

          if [[ $days -lt 7 ]]; then
            echo "Less than 7 days left"
            RENEW=true
          else
            echo "More than 7 days left"
            RENEW=false
          fi

          echo "RENEW -> $RENEW"
          echo "date=$future_date" >> $GITHUB_ENV

      - name: call function
        run: |
          echo "workspace -> ${GITHUB_WORKSPACE}"
          result=$(bash ${GITHUB_WORKSPACE}/scripts/getSum.sh 34 9)
          echo "result is $result"

          result=$(bash ${GITHUB_WORKSPACE}/scripts/getSub.sh 6 2)
          echo "result is $result"

          list=$(bash ${GITHUB_WORKSPACE}/scripts/getList.sh)
          echo "list is $list"

      - name: get days
        run: |
          days=$(bash ${GITHUB_WORKSPACE}/scripts/getDaysToExpiry.sh)
          echo "workflow days -> $days"

          if [[ $days -lt 7 ]]; then
            echo "Less than 7 days left"
            RENEW=true
          else
            echo "More than 7 days left"
            RENEW=false
          fi




      
          


          