name: date-time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
      branches:
        - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1
  name: "nadeem"

jobs:
  DateTime:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version

      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: get expiration date
        run: |    
          jq . reg-time.json
          jq -r '.expiration_date[:10]' reg-time.json
          
          reg-date=$(jq -r '.expiration_date[:10]' reg-time.json)
          echo "exp-date=$reg-date"

          current_days=$(date -d "$(date -u +"%F")" "+%s")

          reg_days=$(date -d "$(jq -r '.expiration_date[:10]' reg-time.json)" "+%s")

          remaining_days="days -> $( ($current_days - $reg_days) / 86400 )"

          if [[ "$remaining_days" < 300 ]]; then
            echo "expired"
          else
            echo "not expired"
          fi


      
          


          