name: date-time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false

jobs:
  DateTime:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get date and time
        run: |
          # get current date and time in UTC
          date -u
          date -u +"%Y-%m-%dT%H:%M:%SZ" > test-time.json
          cat test-time.json
          

      - name: parse json file for current time
        run: |
          ls -l
          jq '.' reg-time.json
          
      # query for expiration_date and put it in a variable
      - name: get expiration date
        run: |      
          jq '.expiration_date' reg-time.json >> exp-date