name: date-time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false

jobs:
  DateTime:
    runs-on: ubuntu-latest
    steps:
      - name: get date and time
        run: |
          reg-time = date -u +"%Y-%m-%d %H:%M:%S %Z"
          echo "The current date and time is $(reg-time)."

          sleep 20
          
          current-time = date -u +"%Y-%m-%d %H:%M:%S %Z"
          echo "The current date and time is $(current-time)."
