name: date-time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1
  name: "nadeem"

jobs:
  DateTime:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get date and time (json)
        run: |
          # get current date and time in UTC
          test-date=$(date -u +"%Y-%m-%d")
          echo "test-date=$test-date"
          
      # query for expiration_date and put it in a variable
      - name: get expiration date
        run: |    
          reg-date=$(jq '.expiration_date[:10]' reg-time.json)
          echo "reg-date=$reg-date"
        
          reg-days=$(date -d "$(jq -r '.expiration_date[:10]' reg-time.json)" "+%s")
          test-days=$(date -d "$test-date" "+%s")

          echo "reg-days=$reg-days"
          echo "test-days=$test-days"

          remaining-days=$((reg-days - test-days))
          echo "remaining-days=$remaining-days"

      
          


          