name: date-time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
      branches:
        - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1
  name: "nadeem"

jobs:
  DateTime:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get sum
        run: |
          echo "call sum function"
          sum=$(bash ${GITHUB_WORKSPACE}/scripts/getSum.sh 34 9)
          echo "sum -> $sum"

      - name: step vars
        id: vars
        run: |
          last="khalid"
          svar=$(bash ${GITHUB_WORKSPACE}/scripts/stepVars.sh)
          echo "svar -> $svar"
          echo "last=$last" >> $GITHUB_OUTPUT

      - name: get list
        env: 
            cat: "Tiger"
            first_name: ${{ env.name }}
            last_name: ${{ steps.vars.outputs.last }}
            fgw_name: $fgw_name_c
        run: |
          fgw_name='fgw-regionsbank-dev'
          for counter in {1..5}: do
            fgw_name_c="$fgw_name'-$counter'"
            echo "fgw_name_c -> $fgw_name_c"
            bash ${GITHUB_WORKSPACE}/scripts/getList.sh $fgw_name_c
          done
        

            

      - name: get days
        run: |    
          jq . reg-time.json
          days_to_expiry=$(bash ${GITHUB_WORKSPACE}/scripts/getDaysToExpiry.sh)
          
          echo "days_to_expiry -> $days_to_expiry"

          if [[ $days_to_expiry -lt 7 ]]; then
            echo "Less than 7 days left"
            RENEW=true
          else
            echo "More than 7 days left"
            RENEW=false
          fi

      - name: http code
        run: |
          http_code=$(bash ${GITHUB_WORKSPACE}/scripts/getHttpCode.sh)
          echo "http_code -> $http_code"
          




      
          


          