name: register & store

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  BG: nk
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      actions: write  # read|write|none
      checks: write  # read|write|none
      contents: write  # read|write|none
      deployments: write  # read|write|none
      id-token: write  # read|write|none
      issues: write  # read|write|none
      discussions: write  # read|write|none
      packages: write # read|write|none
      pages: write  # read|write|none
      pull-requests: write  # read|write|none
      repository-projects: write  # read|write|none
      security-events: write  # read|write|none
      statuses: write  # read|write|none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: pull image
        run: |
          docker pull mulesoft/flex-gateway:latest

      # list docker images
      - name: list docker images
        run: |
          docker images

      # check os version on ubuntu
      - name: check os version
        run: |
          cat /etc/os-release

      - name: make directory
        run: |
          mkdir -p temp
          echo "Hello, World!" > temp/hello.txt
          ls -l

      - name: register
        run: |
          sudo docker run --entrypoint flexctl -u $UID \
            -v "$(pwd)/registration-1":/registration mulesoft/flex-gateway \
            registration create --organization=a6ea8ce7-6d5f-41ee-a802-5505e8833854 \
            --token=6ef662dd-3a28-4f34-b0ae-2135ba3e53ff \
            --output-directory=/registration \
            --connected=true \
            ci-gw-1

      
