name: register & store

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false

jobs:
  register:
    runs-on: ubuntu-latest
    permissions:
      actions: write # read|write|none
      checks: write # read|write|none
      contents: write # read|write|none
      deployments: write # read|write|none
      id-token: write # read|write|none
      issues: write # read|write|none
      discussions: write # read|write|none
      packages: write # read|write|none
      pages: write # read|write|none
      pull-requests: write # read|write|none
      repository-projects: write # read|write|none
      security-events: write # read|write|none
      statuses: write # read|write|none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: pull image
        run: |
          docker pull mulesoft/flex-gateway:latest

      # list docker images
      - name: list docker images
        run: |
          docker images

      # check os version on ubuntu
      - name: check os version
        run: |
          cat /etc/os-release

      - name: make directory
        run: |
          mkdir -p temp
          mkdir -p renew
          ls -l

      # docker container run [OPTIONS] IMAGE [COMMAND] [ARG...]
      # Aliases: docker run

      - name: register
        run: |
          sudo docker run --entrypoint flexctl \
            -v "$(pwd)/temp":/registration -u $UID mulesoft/flex-gateway \
            registration create \
            --client-id=b95726291f564ae2942ac2c4ecc46311 \
            --client-secret=59dB6D7A84bd442bAfE7422233a82902 \
            --environment=2c6f18bb-03e2-4874-a489-7216df5b5bc2 \
            --connected=true \
            --organization=a6ea8ce7-6d5f-41ee-a802-5505e8833854 \
            --output-directory=/registration \
            gateway-9

      - name: list files
        run: |
          ls -l

      - name: push to Artifactory
        run: |
          cat temp/registration.yaml
          # zip registration.yaml
          zip -r registration.zip temp/registration.yaml
          ls -l

      - name: wait
        run: |
          sleep 5

      # inspect registration.yaml
      - name: inspection
        run: |
          sudo docker run --entrypoint flexctl \
            -v "$(pwd)/temp":/registration \
            -u $UID mulesoft/flex-gateway \
            registration inspect --file=/registration/registration.yaml > reg-date.yaml

      - name: renew
        run: |
          sudo docker run --entrypoint flexctl \
            -v "$(pwd)":/renew \
            -v "$(pwd)/temp":/registration \
            -u $UID mulesoft/flex-gateway \
            registration renew \
            --client-id=b95726291f564ae2942ac2c4ecc46311 \
            --client-secret=59dB6D7A84bd442bAfE7422233a82902 \
            --output-directory=/renew \
            /registration/registration.yaml

      - name: push new registration to Artifactory
        run: |
          cat registration.yaml
          # zip registration.yaml
          zip -r registration-new.zip registration.yaml
          ls -l
          
                      

      
