name: jq-test

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1

jobs:
  JsonTest:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make json
        run: |
          regyaml="test"
          configyaml="test2"
          echo "{}" > config.json
          echo "$(jq --arg regyaml "$regyaml", --arg configyaml "$configyaml"  '. += {"regyaml": $regyaml, "configyaml": $configyaml}' config.json)" > config.json
          jq . config.json


      