name: json-test

on:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1
  name: "nadeem"

jobs:
  JsonTest:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make json
        run: |
          client_id=349759438579347
          client_id=349759438579
          json_string=$"{\"client_id\":$client_id,\"client_id\":$client_id}"
          echo "json_string -> $json_string"

          echo $json_string > login.json
          jq . login.json

      