name: json-test

on:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1
  name: "nadeem"

jobs:
  JsonTest:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make json
        run: |
          name="John"
          age=30
          # Create a simple JSON string
          json_string='{"name": $name, "age": $age}'
          echo $json_string

          # Write the JSON string to a file
          echo $json_string > data.json

      