name: json-test

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1
  name: "nadeem"

jobs:
  JsonTest:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make json
        run: |
          client_id=349759438579347
          client_secret=349759438579
          echo "{\"client_id\":\"$client_id\",\"client_secret\":\"$client_secret\"}" > login.json
          jq . login.json

      