name: loop-test

on:
  push:
    branches:
      - main

env:
  count: 4
  name: "test"

jobs:
  loop:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none

    steps:
      - name: for loop
        run: |
          for counter in {1..4}; do
            url="/v1/abc/${{env.count}}-${{ env.name }}/$counter"
            echo "url -> $url"
            
          done
