name: loop-test

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  count: 4
  name: "test"

jobs:
  loop:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none

    steps:
      - name: for loop
        run: |
          for counter in {1..4}; do
            nk="${{env.count}}-${{ env.name }}/$counter"
            url="/v1/abc/${{ github.event_name }}/$nk"
            echo "url -> $url"
            
          done
