name: loop-test

on:
  push:
    branches:
      - main

env:
  count: 4

jobs:
  loop:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:
          
      - name: for loop
        run: |
          for conter in {1..4}; do
            url="$(https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)"
            echo "url -> $url"
            url="${{env.count}}/$counter"
            echo "url -> $url"
            
          done
