name: register

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  
  request-reg:
    uses: nk1752/flex-registration/.github/workflows/reg-reusable.yml@main
    with:
      bg: nadeem
      env: dev
