name: input test

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'TAG version'
        type: string
        required: false

jobs:
  pull-flex:
    # do not run on pull request
    if: (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
    
    steps:

      - name: test input
        run: |
          if [ "${{ inputs.TAG }}" == null ]; then
            echo "TAG is empty"
          else
            echo "TAG is not empty"
          fi
      