name: variables

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  id: 1
  name: "nadeem"

jobs:
  DateTime:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version

      - name: build variables
        run: |
          echo "q1=\"id=$id, \"name\"=$name" >> $GITHUB_ENV
          echo "RENEW=$RENEW" >> $GITHUB_ENV

          echo "env id: ${{ env.id }}"
          echo "env name: ${{ env.name }}"
          echo "env renew: ${{ env.RENEW }}"
          echo "env q1: ${{ env.q1 }}"