name: env -> variables

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  ID: 1
  NAME: "nadeem"

jobs:
  Variables:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:
      - name: Set dynamic variable
        run: echo "DYNAMIC_VAR=dynamic value" >> $GITHUB_ENV

      - name: Use dynamic variable
        run: echo $DYNAMIC_VAR

      - name: Set dynamic variable 1
        run: |
          echo "NAME1=inaaya" >> $GITHUB_ENV
          echo "NAME2=nadeem" >> $GITHUB_ENV
          
      - name: display dynamic variable 1
        run: |
          echo NAME1 --> $NAME1    
          echo NAME2 --> $NAME2
          
      - name: build json file
        run: |
      
          echo "{}" > config.json

          jq --arg name "$NAME1" '. += {"name1": $name}' config.json > config.json
          jq --arg name "$NAME2" '. += {"name2": $name}' config.json > config.json
          jq . config.json


          
          