name: env -> variables

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  ID: 1
  NAME: "rashida"
  BG: "blue"
  ENV: "dev"

jobs:
  Variables:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:
      - name: Set dynamic variable 1
        run: |
          echo "NAME1=inaaya" >> $GITHUB_ENV
          echo "NAME2=nadeem" >> $GITHUB_ENV
          
      - name: display dynamic variable 1
        run: |
          echo NAME1 --> $NAME1    
          echo NAME2 --> $NAME2
          
      - name: build json file
        
        run: |
      
          echo "{}" > config.json

          echo "$(jq --arg name "$NAME1" --arg env "$ENV" '. += { "obj1":{"name": $name, "id": 1, "env": $env} }' config.json)" > config.json
              
          echo "$(jq --arg name "$NAME2" '. += { "obj2":{"name": $name, "id": 2} }' config.json)" > config.json
          echo "$(jq --arg name "${{ env.NAME }}" '. += { "obj3":{"name": $name, "id": 3} }' config.json)" > config.json
          jq . config.json

          
          # check for true or false in bash
          if [[ $RENEW == "true" ]]; then
            echo "RENEW is true"
          else
            echo "RENEW is false"
          fi
          
          if [[1 eq 2]]; then
            echo "obj21 does exists"
          else
            echo "obj21 does NOT exist"
          fi

          if [[1 eq 1]]; then
            echo "obj21 does exists"
          else
            echo "obj21 does NOT exist"
          fi

         


          
          