name: env -> variables

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  ID: 1
  NAME: "nadeem"

jobs:
  Variables:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version

      - name: build variables
        run: |
          echo " q1=\"id\"=${{ env.ID }} " >> $GITHUB_ENV
          echo "q2=query2" >> $GITHUB_ENV

          echo "q1 -->: $q1"
          echo "q2 -->: $q2"
          