name: env -> variables

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  ID: 1
  NAME: "nadeem"

jobs:
  Variables:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:
      - name: Set dynamic variable
        run: echo "DYNAMIC_VAR=dynamic value" >> $GITHUB_ENV

      - name: Use dynamic variable
        run: echo $DYNAMIC_VAR

      - name: Set dynamic variable 1
        run: |
          echo "DID=5" >> $GITHUB_ENV
          echo "DNAME=nadeem" >> $GITHUB_ENV
          
      - name: display dynamic variable 1
        run: |
          echo DID --> $DID    
          echo DNAME --> $DNAME
          
      - name: build json file
        run: |
      
          echo {} > test.json
          jq . test.json

          jq '. += {"name": "Inaaya"}' test.json > temp.json
          cat temp.json > test.json

          jq . test.json

          jq '. += {"name": "nadeem"}' test.json > temp.json
          cat temp.json > test.json

          jq . test.json


          
          