name: env -> variables

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: false
  ID: 1
  NAME: "nadeem"

jobs:
  Variables:
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:

      - name: Set dynamic variable
        run: |
          echo "DYNAMIC_VAR=dynamic value" >> $GITHUB_ENV
          echo "DYNAMIC_VAR_1=dynamic value 1" >> $GITHUB_ENV
          echo "DYNAMIC_VAR_3=${{ env.NAME }}" >> $GITHUB_ENV
          echo "E1=\"id\": ${{ env.ID }}" >> $GITHUB_ENV
          echo "E2=\"${{ env.NAME }}\"" >> $GITHUB_ENV
          
          echo $DYNAMIC_VAR
          echo $DYNAMIC_VAR_1
          echo $DYNAMIC_VAR_3
          echo $E1
          echo $E2

      
          echo {} > test.json
          jq . test.json

          jq '. += {"name": "Inaaya"}' test.json > test.json
          jq '. += {"id": 2}' test.json > test.json
          

          jq . test.json
          